/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index'
import { Route as authOtpImport } from './routes/(auth)/otp'
import { Route as AuthenticatedChatsIndexImport } from './routes/_authenticated/chats/index'
import { Route as authRestablecerContrasenaTokenImport } from './routes/(auth)/restablecer-contrasena.$token'
import { Route as authLinkIniciarSesionTokenImport } from './routes/(auth)/link-iniciar-sesion.$token'

// Create Virtual Routes

const ClientPortalAccessLazyImport = createFileRoute('/client-portal/access')()
const AuthenticatedDashboardLazyImport = createFileRoute(
  '/_authenticated/dashboard',
)()
const errors503LazyImport = createFileRoute('/(errors)/503')()
const errors500LazyImport = createFileRoute('/(errors)/500')()
const errors404LazyImport = createFileRoute('/(errors)/404')()
const errors403LazyImport = createFileRoute('/(errors)/403')()
const errors401LazyImport = createFileRoute('/(errors)/401')()
const authSignUpLazyImport = createFileRoute('/(auth)/sign-up')()
const authRegistrarNegocioLazyImport = createFileRoute(
  '/(auth)/registrar-negocio',
)()
const authRecuperarCuentaLazyImport = createFileRoute(
  '/(auth)/recuperar-cuenta',
)()
const authIniciarSesionLazyImport = createFileRoute('/(auth)/iniciar-sesion')()
const AuthenticatedSettingsRouteLazyImport = createFileRoute(
  '/_authenticated/settings',
)()
const AuthenticatedVentasIndexLazyImport = createFileRoute(
  '/_authenticated/ventas/',
)()
const AuthenticatedToolsIndexLazyImport = createFileRoute(
  '/_authenticated/tools/',
)()
const AuthenticatedSettingsIndexLazyImport = createFileRoute(
  '/_authenticated/settings/',
)()
const AuthenticatedServiciosIndexLazyImport = createFileRoute(
  '/_authenticated/servicios/',
)()
const AuthenticatedProductosIndexLazyImport = createFileRoute(
  '/_authenticated/productos/',
)()
const AuthenticatedPaquetesIndexLazyImport = createFileRoute(
  '/_authenticated/paquetes/',
)()
const AuthenticatedOrdenIndexLazyImport = createFileRoute(
  '/_authenticated/orden/',
)()
const AuthenticatedEventosIndexLazyImport = createFileRoute(
  '/_authenticated/eventos/',
)()
const AuthenticatedEmpleadosIndexLazyImport = createFileRoute(
  '/_authenticated/empleados/',
)()
const AuthenticatedClientesIndexLazyImport = createFileRoute(
  '/_authenticated/clientes/',
)()
const AuthenticatedCitasIndexLazyImport = createFileRoute(
  '/_authenticated/citas/',
)()
const AuthenticatedSettingsWhatsappLazyImport = createFileRoute(
  '/_authenticated/settings/whatsapp',
)()
const AuthenticatedSettingsUnitsLazyImport = createFileRoute(
  '/_authenticated/settings/units',
)()
const AuthenticatedSettingsTagsLazyImport = createFileRoute(
  '/_authenticated/settings/tags',
)()
const AuthenticatedSettingsRolesLazyImport = createFileRoute(
  '/_authenticated/settings/roles',
)()
const AuthenticatedSettingsQuickResponsesLazyImport = createFileRoute(
  '/_authenticated/settings/quick-responses',
)()
const AuthenticatedSettingsMessageTemplatesLazyImport = createFileRoute(
  '/_authenticated/settings/message-templates',
)()
const AuthenticatedSettingsConversationStatusesLazyImport = createFileRoute(
  '/_authenticated/settings/conversation-statuses',
)()
const AuthenticatedSettingsCategoriesLazyImport = createFileRoute(
  '/_authenticated/settings/categories',
)()
const AuthenticatedSettingsAiAssistantLazyImport = createFileRoute(
  '/_authenticated/settings/ai-assistant',
)()
const AuthenticatedSettingsAccountLazyImport = createFileRoute(
  '/_authenticated/settings/account',
)()
const AuthenticatedOrdenHistorialLazyImport = createFileRoute(
  '/_authenticated/orden/historial',
)()

// Create/Update Routes

const AuthenticatedRouteRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const ClientPortalAccessLazyRoute = ClientPortalAccessLazyImport.update({
  id: '/client-portal/access',
  path: '/client-portal/access',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/client-portal/access.lazy').then((d) => d.Route),
)

const AuthenticatedDashboardLazyRoute = AuthenticatedDashboardLazyImport.update(
  {
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any,
).lazy(() =>
  import('./routes/_authenticated/dashboard.lazy').then((d) => d.Route),
)

const errors503LazyRoute = errors503LazyImport
  .update({
    id: '/(errors)/503',
    path: '/503',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/503.lazy').then((d) => d.Route))

const errors500LazyRoute = errors500LazyImport
  .update({
    id: '/(errors)/500',
    path: '/500',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/500.lazy').then((d) => d.Route))

const errors404LazyRoute = errors404LazyImport
  .update({
    id: '/(errors)/404',
    path: '/404',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/404.lazy').then((d) => d.Route))

const errors403LazyRoute = errors403LazyImport
  .update({
    id: '/(errors)/403',
    path: '/403',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/403.lazy').then((d) => d.Route))

const errors401LazyRoute = errors401LazyImport
  .update({
    id: '/(errors)/401',
    path: '/401',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/401.lazy').then((d) => d.Route))

const authSignUpLazyRoute = authSignUpLazyImport
  .update({
    id: '/(auth)/sign-up',
    path: '/sign-up',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(auth)/sign-up.lazy').then((d) => d.Route))

const authRegistrarNegocioLazyRoute = authRegistrarNegocioLazyImport
  .update({
    id: '/(auth)/registrar-negocio',
    path: '/registrar-negocio',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() =>
    import('./routes/(auth)/registrar-negocio.lazy').then((d) => d.Route),
  )

const authRecuperarCuentaLazyRoute = authRecuperarCuentaLazyImport
  .update({
    id: '/(auth)/recuperar-cuenta',
    path: '/recuperar-cuenta',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() =>
    import('./routes/(auth)/recuperar-cuenta.lazy').then((d) => d.Route),
  )

const authIniciarSesionLazyRoute = authIniciarSesionLazyImport
  .update({
    id: '/(auth)/iniciar-sesion',
    path: '/iniciar-sesion',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() =>
    import('./routes/(auth)/iniciar-sesion.lazy').then((d) => d.Route),
  )

const AuthenticatedSettingsRouteLazyRoute =
  AuthenticatedSettingsRouteLazyImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/route.lazy').then((d) => d.Route),
  )

const authOtpRoute = authOtpImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedVentasIndexLazyRoute =
  AuthenticatedVentasIndexLazyImport.update({
    id: '/ventas/',
    path: '/ventas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/ventas/index.lazy').then((d) => d.Route),
  )

const AuthenticatedToolsIndexLazyRoute =
  AuthenticatedToolsIndexLazyImport.update({
    id: '/tools/',
    path: '/tools/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/tools/index.lazy').then((d) => d.Route),
  )

const AuthenticatedSettingsIndexLazyRoute =
  AuthenticatedSettingsIndexLazyImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/index.lazy').then((d) => d.Route),
  )

const AuthenticatedServiciosIndexLazyRoute =
  AuthenticatedServiciosIndexLazyImport.update({
    id: '/servicios/',
    path: '/servicios/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/servicios/index.lazy').then((d) => d.Route),
  )

const AuthenticatedProductosIndexLazyRoute =
  AuthenticatedProductosIndexLazyImport.update({
    id: '/productos/',
    path: '/productos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/productos/index.lazy').then((d) => d.Route),
  )

const AuthenticatedPaquetesIndexLazyRoute =
  AuthenticatedPaquetesIndexLazyImport.update({
    id: '/paquetes/',
    path: '/paquetes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/paquetes/index.lazy').then((d) => d.Route),
  )

const AuthenticatedOrdenIndexLazyRoute =
  AuthenticatedOrdenIndexLazyImport.update({
    id: '/orden/',
    path: '/orden/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/orden/index.lazy').then((d) => d.Route),
  )

const AuthenticatedEventosIndexLazyRoute =
  AuthenticatedEventosIndexLazyImport.update({
    id: '/eventos/',
    path: '/eventos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/eventos/index.lazy').then((d) => d.Route),
  )

const AuthenticatedEmpleadosIndexLazyRoute =
  AuthenticatedEmpleadosIndexLazyImport.update({
    id: '/empleados/',
    path: '/empleados/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/empleados/index.lazy').then((d) => d.Route),
  )

const AuthenticatedClientesIndexLazyRoute =
  AuthenticatedClientesIndexLazyImport.update({
    id: '/clientes/',
    path: '/clientes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/clientes/index.lazy').then((d) => d.Route),
  )

const AuthenticatedCitasIndexLazyRoute =
  AuthenticatedCitasIndexLazyImport.update({
    id: '/citas/',
    path: '/citas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/citas/index.lazy').then((d) => d.Route),
  )

const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedSettingsWhatsappLazyRoute =
  AuthenticatedSettingsWhatsappLazyImport.update({
    id: '/whatsapp',
    path: '/whatsapp',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/whatsapp.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedSettingsUnitsLazyRoute =
  AuthenticatedSettingsUnitsLazyImport.update({
    id: '/units',
    path: '/units',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/units.lazy').then((d) => d.Route),
  )

const AuthenticatedSettingsTagsLazyRoute =
  AuthenticatedSettingsTagsLazyImport.update({
    id: '/tags',
    path: '/tags',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/tags.lazy').then((d) => d.Route),
  )

const AuthenticatedSettingsRolesLazyRoute =
  AuthenticatedSettingsRolesLazyImport.update({
    id: '/roles',
    path: '/roles',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/roles.lazy').then((d) => d.Route),
  )

const AuthenticatedSettingsQuickResponsesLazyRoute =
  AuthenticatedSettingsQuickResponsesLazyImport.update({
    id: '/quick-responses',
    path: '/quick-responses',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/quick-responses.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedSettingsMessageTemplatesLazyRoute =
  AuthenticatedSettingsMessageTemplatesLazyImport.update({
    id: '/message-templates',
    path: '/message-templates',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/message-templates.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedSettingsConversationStatusesLazyRoute =
  AuthenticatedSettingsConversationStatusesLazyImport.update({
    id: '/conversation-statuses',
    path: '/conversation-statuses',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/conversation-statuses.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedSettingsCategoriesLazyRoute =
  AuthenticatedSettingsCategoriesLazyImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/categories.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedSettingsAiAssistantLazyRoute =
  AuthenticatedSettingsAiAssistantLazyImport.update({
    id: '/ai-assistant',
    path: '/ai-assistant',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/ai-assistant.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedSettingsAccountLazyRoute =
  AuthenticatedSettingsAccountLazyImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/account.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedOrdenHistorialLazyRoute =
  AuthenticatedOrdenHistorialLazyImport.update({
    id: '/orden/historial',
    path: '/orden/historial',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/orden/historial.lazy').then((d) => d.Route),
  )

const authRestablecerContrasenaTokenRoute =
  authRestablecerContrasenaTokenImport.update({
    id: '/(auth)/restablecer-contrasena/$token',
    path: '/restablecer-contrasena/$token',
    getParentRoute: () => rootRoute,
  } as any)

const authLinkIniciarSesionTokenRoute = authLinkIniciarSesionTokenImport.update(
  {
    id: '/(auth)/link-iniciar-sesion/$token',
    path: '/link-iniciar-sesion/$token',
    getParentRoute: () => rootRoute,
  } as any,
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/(auth)/iniciar-sesion': {
      id: '/(auth)/iniciar-sesion'
      path: '/iniciar-sesion'
      fullPath: '/iniciar-sesion'
      preLoaderRoute: typeof authIniciarSesionLazyImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/recuperar-cuenta': {
      id: '/(auth)/recuperar-cuenta'
      path: '/recuperar-cuenta'
      fullPath: '/recuperar-cuenta'
      preLoaderRoute: typeof authRecuperarCuentaLazyImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/registrar-negocio': {
      id: '/(auth)/registrar-negocio'
      path: '/registrar-negocio'
      fullPath: '/registrar-negocio'
      preLoaderRoute: typeof authRegistrarNegocioLazyImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpLazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503LazyImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/client-portal/access': {
      id: '/client-portal/access'
      path: '/client-portal/access'
      fullPath: '/client-portal/access'
      preLoaderRoute: typeof ClientPortalAccessLazyImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/(auth)/link-iniciar-sesion/$token': {
      id: '/(auth)/link-iniciar-sesion/$token'
      path: '/link-iniciar-sesion/$token'
      fullPath: '/link-iniciar-sesion/$token'
      preLoaderRoute: typeof authLinkIniciarSesionTokenImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/restablecer-contrasena/$token': {
      id: '/(auth)/restablecer-contrasena/$token'
      path: '/restablecer-contrasena/$token'
      fullPath: '/restablecer-contrasena/$token'
      preLoaderRoute: typeof authRestablecerContrasenaTokenImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/orden/historial': {
      id: '/_authenticated/orden/historial'
      path: '/orden/historial'
      fullPath: '/orden/historial'
      preLoaderRoute: typeof AuthenticatedOrdenHistorialLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountLazyImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/settings/ai-assistant': {
      id: '/_authenticated/settings/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/settings/ai-assistant'
      preLoaderRoute: typeof AuthenticatedSettingsAiAssistantLazyImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/settings/categories': {
      id: '/_authenticated/settings/categories'
      path: '/categories'
      fullPath: '/settings/categories'
      preLoaderRoute: typeof AuthenticatedSettingsCategoriesLazyImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/settings/conversation-statuses': {
      id: '/_authenticated/settings/conversation-statuses'
      path: '/conversation-statuses'
      fullPath: '/settings/conversation-statuses'
      preLoaderRoute: typeof AuthenticatedSettingsConversationStatusesLazyImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/settings/message-templates': {
      id: '/_authenticated/settings/message-templates'
      path: '/message-templates'
      fullPath: '/settings/message-templates'
      preLoaderRoute: typeof AuthenticatedSettingsMessageTemplatesLazyImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/settings/quick-responses': {
      id: '/_authenticated/settings/quick-responses'
      path: '/quick-responses'
      fullPath: '/settings/quick-responses'
      preLoaderRoute: typeof AuthenticatedSettingsQuickResponsesLazyImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/settings/roles': {
      id: '/_authenticated/settings/roles'
      path: '/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof AuthenticatedSettingsRolesLazyImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/settings/tags': {
      id: '/_authenticated/settings/tags'
      path: '/tags'
      fullPath: '/settings/tags'
      preLoaderRoute: typeof AuthenticatedSettingsTagsLazyImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/settings/units': {
      id: '/_authenticated/settings/units'
      path: '/units'
      fullPath: '/settings/units'
      preLoaderRoute: typeof AuthenticatedSettingsUnitsLazyImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/settings/whatsapp': {
      id: '/_authenticated/settings/whatsapp'
      path: '/whatsapp'
      fullPath: '/settings/whatsapp'
      preLoaderRoute: typeof AuthenticatedSettingsWhatsappLazyImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/citas/': {
      id: '/_authenticated/citas/'
      path: '/citas'
      fullPath: '/citas'
      preLoaderRoute: typeof AuthenticatedCitasIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/clientes/': {
      id: '/_authenticated/clientes/'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/empleados/': {
      id: '/_authenticated/empleados/'
      path: '/empleados'
      fullPath: '/empleados'
      preLoaderRoute: typeof AuthenticatedEmpleadosIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/eventos/': {
      id: '/_authenticated/eventos/'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof AuthenticatedEventosIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/orden/': {
      id: '/_authenticated/orden/'
      path: '/orden'
      fullPath: '/orden'
      preLoaderRoute: typeof AuthenticatedOrdenIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/paquetes/': {
      id: '/_authenticated/paquetes/'
      path: '/paquetes'
      fullPath: '/paquetes'
      preLoaderRoute: typeof AuthenticatedPaquetesIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/productos/': {
      id: '/_authenticated/productos/'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof AuthenticatedProductosIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/servicios/': {
      id: '/_authenticated/servicios/'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof AuthenticatedServiciosIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexLazyImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/tools/': {
      id: '/_authenticated/tools/'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof AuthenticatedToolsIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/ventas/': {
      id: '/_authenticated/ventas/'
      path: '/ventas'
      fullPath: '/ventas'
      preLoaderRoute: typeof AuthenticatedVentasIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedSettingsRouteLazyRouteChildren {
  AuthenticatedSettingsAccountLazyRoute: typeof AuthenticatedSettingsAccountLazyRoute
  AuthenticatedSettingsAiAssistantLazyRoute: typeof AuthenticatedSettingsAiAssistantLazyRoute
  AuthenticatedSettingsCategoriesLazyRoute: typeof AuthenticatedSettingsCategoriesLazyRoute
  AuthenticatedSettingsConversationStatusesLazyRoute: typeof AuthenticatedSettingsConversationStatusesLazyRoute
  AuthenticatedSettingsMessageTemplatesLazyRoute: typeof AuthenticatedSettingsMessageTemplatesLazyRoute
  AuthenticatedSettingsQuickResponsesLazyRoute: typeof AuthenticatedSettingsQuickResponsesLazyRoute
  AuthenticatedSettingsRolesLazyRoute: typeof AuthenticatedSettingsRolesLazyRoute
  AuthenticatedSettingsTagsLazyRoute: typeof AuthenticatedSettingsTagsLazyRoute
  AuthenticatedSettingsUnitsLazyRoute: typeof AuthenticatedSettingsUnitsLazyRoute
  AuthenticatedSettingsWhatsappLazyRoute: typeof AuthenticatedSettingsWhatsappLazyRoute
  AuthenticatedSettingsIndexLazyRoute: typeof AuthenticatedSettingsIndexLazyRoute
}

const AuthenticatedSettingsRouteLazyRouteChildren: AuthenticatedSettingsRouteLazyRouteChildren =
  {
    AuthenticatedSettingsAccountLazyRoute:
      AuthenticatedSettingsAccountLazyRoute,
    AuthenticatedSettingsAiAssistantLazyRoute:
      AuthenticatedSettingsAiAssistantLazyRoute,
    AuthenticatedSettingsCategoriesLazyRoute:
      AuthenticatedSettingsCategoriesLazyRoute,
    AuthenticatedSettingsConversationStatusesLazyRoute:
      AuthenticatedSettingsConversationStatusesLazyRoute,
    AuthenticatedSettingsMessageTemplatesLazyRoute:
      AuthenticatedSettingsMessageTemplatesLazyRoute,
    AuthenticatedSettingsQuickResponsesLazyRoute:
      AuthenticatedSettingsQuickResponsesLazyRoute,
    AuthenticatedSettingsRolesLazyRoute: AuthenticatedSettingsRolesLazyRoute,
    AuthenticatedSettingsTagsLazyRoute: AuthenticatedSettingsTagsLazyRoute,
    AuthenticatedSettingsUnitsLazyRoute: AuthenticatedSettingsUnitsLazyRoute,
    AuthenticatedSettingsWhatsappLazyRoute:
      AuthenticatedSettingsWhatsappLazyRoute,
    AuthenticatedSettingsIndexLazyRoute: AuthenticatedSettingsIndexLazyRoute,
  }

const AuthenticatedSettingsRouteLazyRouteWithChildren =
  AuthenticatedSettingsRouteLazyRoute._addFileChildren(
    AuthenticatedSettingsRouteLazyRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteLazyRoute: typeof AuthenticatedSettingsRouteLazyRouteWithChildren
  AuthenticatedDashboardLazyRoute: typeof AuthenticatedDashboardLazyRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedOrdenHistorialLazyRoute: typeof AuthenticatedOrdenHistorialLazyRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedCitasIndexLazyRoute: typeof AuthenticatedCitasIndexLazyRoute
  AuthenticatedClientesIndexLazyRoute: typeof AuthenticatedClientesIndexLazyRoute
  AuthenticatedEmpleadosIndexLazyRoute: typeof AuthenticatedEmpleadosIndexLazyRoute
  AuthenticatedEventosIndexLazyRoute: typeof AuthenticatedEventosIndexLazyRoute
  AuthenticatedOrdenIndexLazyRoute: typeof AuthenticatedOrdenIndexLazyRoute
  AuthenticatedPaquetesIndexLazyRoute: typeof AuthenticatedPaquetesIndexLazyRoute
  AuthenticatedProductosIndexLazyRoute: typeof AuthenticatedProductosIndexLazyRoute
  AuthenticatedServiciosIndexLazyRoute: typeof AuthenticatedServiciosIndexLazyRoute
  AuthenticatedToolsIndexLazyRoute: typeof AuthenticatedToolsIndexLazyRoute
  AuthenticatedVentasIndexLazyRoute: typeof AuthenticatedVentasIndexLazyRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteLazyRoute:
    AuthenticatedSettingsRouteLazyRouteWithChildren,
  AuthenticatedDashboardLazyRoute: AuthenticatedDashboardLazyRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedOrdenHistorialLazyRoute: AuthenticatedOrdenHistorialLazyRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedCitasIndexLazyRoute: AuthenticatedCitasIndexLazyRoute,
  AuthenticatedClientesIndexLazyRoute: AuthenticatedClientesIndexLazyRoute,
  AuthenticatedEmpleadosIndexLazyRoute: AuthenticatedEmpleadosIndexLazyRoute,
  AuthenticatedEventosIndexLazyRoute: AuthenticatedEventosIndexLazyRoute,
  AuthenticatedOrdenIndexLazyRoute: AuthenticatedOrdenIndexLazyRoute,
  AuthenticatedPaquetesIndexLazyRoute: AuthenticatedPaquetesIndexLazyRoute,
  AuthenticatedProductosIndexLazyRoute: AuthenticatedProductosIndexLazyRoute,
  AuthenticatedServiciosIndexLazyRoute: AuthenticatedServiciosIndexLazyRoute,
  AuthenticatedToolsIndexLazyRoute: AuthenticatedToolsIndexLazyRoute,
  AuthenticatedVentasIndexLazyRoute: AuthenticatedVentasIndexLazyRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedRouteRouteWithChildren
  '/otp': typeof authOtpRoute
  '/settings': typeof AuthenticatedSettingsRouteLazyRouteWithChildren
  '/iniciar-sesion': typeof authIniciarSesionLazyRoute
  '/recuperar-cuenta': typeof authRecuperarCuentaLazyRoute
  '/registrar-negocio': typeof authRegistrarNegocioLazyRoute
  '/sign-up': typeof authSignUpLazyRoute
  '/401': typeof errors401LazyRoute
  '/403': typeof errors403LazyRoute
  '/404': typeof errors404LazyRoute
  '/500': typeof errors500LazyRoute
  '/503': typeof errors503LazyRoute
  '/dashboard': typeof AuthenticatedDashboardLazyRoute
  '/client-portal/access': typeof ClientPortalAccessLazyRoute
  '/': typeof AuthenticatedIndexRoute
  '/link-iniciar-sesion/$token': typeof authLinkIniciarSesionTokenRoute
  '/restablecer-contrasena/$token': typeof authRestablecerContrasenaTokenRoute
  '/orden/historial': typeof AuthenticatedOrdenHistorialLazyRoute
  '/settings/account': typeof AuthenticatedSettingsAccountLazyRoute
  '/settings/ai-assistant': typeof AuthenticatedSettingsAiAssistantLazyRoute
  '/settings/categories': typeof AuthenticatedSettingsCategoriesLazyRoute
  '/settings/conversation-statuses': typeof AuthenticatedSettingsConversationStatusesLazyRoute
  '/settings/message-templates': typeof AuthenticatedSettingsMessageTemplatesLazyRoute
  '/settings/quick-responses': typeof AuthenticatedSettingsQuickResponsesLazyRoute
  '/settings/roles': typeof AuthenticatedSettingsRolesLazyRoute
  '/settings/tags': typeof AuthenticatedSettingsTagsLazyRoute
  '/settings/units': typeof AuthenticatedSettingsUnitsLazyRoute
  '/settings/whatsapp': typeof AuthenticatedSettingsWhatsappLazyRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/citas': typeof AuthenticatedCitasIndexLazyRoute
  '/clientes': typeof AuthenticatedClientesIndexLazyRoute
  '/empleados': typeof AuthenticatedEmpleadosIndexLazyRoute
  '/eventos': typeof AuthenticatedEventosIndexLazyRoute
  '/orden': typeof AuthenticatedOrdenIndexLazyRoute
  '/paquetes': typeof AuthenticatedPaquetesIndexLazyRoute
  '/productos': typeof AuthenticatedProductosIndexLazyRoute
  '/servicios': typeof AuthenticatedServiciosIndexLazyRoute
  '/settings/': typeof AuthenticatedSettingsIndexLazyRoute
  '/tools': typeof AuthenticatedToolsIndexLazyRoute
  '/ventas': typeof AuthenticatedVentasIndexLazyRoute
}

export interface FileRoutesByTo {
  '/otp': typeof authOtpRoute
  '/iniciar-sesion': typeof authIniciarSesionLazyRoute
  '/recuperar-cuenta': typeof authRecuperarCuentaLazyRoute
  '/registrar-negocio': typeof authRegistrarNegocioLazyRoute
  '/sign-up': typeof authSignUpLazyRoute
  '/401': typeof errors401LazyRoute
  '/403': typeof errors403LazyRoute
  '/404': typeof errors404LazyRoute
  '/500': typeof errors500LazyRoute
  '/503': typeof errors503LazyRoute
  '/dashboard': typeof AuthenticatedDashboardLazyRoute
  '/client-portal/access': typeof ClientPortalAccessLazyRoute
  '/': typeof AuthenticatedIndexRoute
  '/link-iniciar-sesion/$token': typeof authLinkIniciarSesionTokenRoute
  '/restablecer-contrasena/$token': typeof authRestablecerContrasenaTokenRoute
  '/orden/historial': typeof AuthenticatedOrdenHistorialLazyRoute
  '/settings/account': typeof AuthenticatedSettingsAccountLazyRoute
  '/settings/ai-assistant': typeof AuthenticatedSettingsAiAssistantLazyRoute
  '/settings/categories': typeof AuthenticatedSettingsCategoriesLazyRoute
  '/settings/conversation-statuses': typeof AuthenticatedSettingsConversationStatusesLazyRoute
  '/settings/message-templates': typeof AuthenticatedSettingsMessageTemplatesLazyRoute
  '/settings/quick-responses': typeof AuthenticatedSettingsQuickResponsesLazyRoute
  '/settings/roles': typeof AuthenticatedSettingsRolesLazyRoute
  '/settings/tags': typeof AuthenticatedSettingsTagsLazyRoute
  '/settings/units': typeof AuthenticatedSettingsUnitsLazyRoute
  '/settings/whatsapp': typeof AuthenticatedSettingsWhatsappLazyRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/citas': typeof AuthenticatedCitasIndexLazyRoute
  '/clientes': typeof AuthenticatedClientesIndexLazyRoute
  '/empleados': typeof AuthenticatedEmpleadosIndexLazyRoute
  '/eventos': typeof AuthenticatedEventosIndexLazyRoute
  '/orden': typeof AuthenticatedOrdenIndexLazyRoute
  '/paquetes': typeof AuthenticatedPaquetesIndexLazyRoute
  '/productos': typeof AuthenticatedProductosIndexLazyRoute
  '/servicios': typeof AuthenticatedServiciosIndexLazyRoute
  '/settings': typeof AuthenticatedSettingsIndexLazyRoute
  '/tools': typeof AuthenticatedToolsIndexLazyRoute
  '/ventas': typeof AuthenticatedVentasIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/otp': typeof authOtpRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteLazyRouteWithChildren
  '/(auth)/iniciar-sesion': typeof authIniciarSesionLazyRoute
  '/(auth)/recuperar-cuenta': typeof authRecuperarCuentaLazyRoute
  '/(auth)/registrar-negocio': typeof authRegistrarNegocioLazyRoute
  '/(auth)/sign-up': typeof authSignUpLazyRoute
  '/(errors)/401': typeof errors401LazyRoute
  '/(errors)/403': typeof errors403LazyRoute
  '/(errors)/404': typeof errors404LazyRoute
  '/(errors)/500': typeof errors500LazyRoute
  '/(errors)/503': typeof errors503LazyRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardLazyRoute
  '/client-portal/access': typeof ClientPortalAccessLazyRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/(auth)/link-iniciar-sesion/$token': typeof authLinkIniciarSesionTokenRoute
  '/(auth)/restablecer-contrasena/$token': typeof authRestablecerContrasenaTokenRoute
  '/_authenticated/orden/historial': typeof AuthenticatedOrdenHistorialLazyRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountLazyRoute
  '/_authenticated/settings/ai-assistant': typeof AuthenticatedSettingsAiAssistantLazyRoute
  '/_authenticated/settings/categories': typeof AuthenticatedSettingsCategoriesLazyRoute
  '/_authenticated/settings/conversation-statuses': typeof AuthenticatedSettingsConversationStatusesLazyRoute
  '/_authenticated/settings/message-templates': typeof AuthenticatedSettingsMessageTemplatesLazyRoute
  '/_authenticated/settings/quick-responses': typeof AuthenticatedSettingsQuickResponsesLazyRoute
  '/_authenticated/settings/roles': typeof AuthenticatedSettingsRolesLazyRoute
  '/_authenticated/settings/tags': typeof AuthenticatedSettingsTagsLazyRoute
  '/_authenticated/settings/units': typeof AuthenticatedSettingsUnitsLazyRoute
  '/_authenticated/settings/whatsapp': typeof AuthenticatedSettingsWhatsappLazyRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/citas/': typeof AuthenticatedCitasIndexLazyRoute
  '/_authenticated/clientes/': typeof AuthenticatedClientesIndexLazyRoute
  '/_authenticated/empleados/': typeof AuthenticatedEmpleadosIndexLazyRoute
  '/_authenticated/eventos/': typeof AuthenticatedEventosIndexLazyRoute
  '/_authenticated/orden/': typeof AuthenticatedOrdenIndexLazyRoute
  '/_authenticated/paquetes/': typeof AuthenticatedPaquetesIndexLazyRoute
  '/_authenticated/productos/': typeof AuthenticatedProductosIndexLazyRoute
  '/_authenticated/servicios/': typeof AuthenticatedServiciosIndexLazyRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexLazyRoute
  '/_authenticated/tools/': typeof AuthenticatedToolsIndexLazyRoute
  '/_authenticated/ventas/': typeof AuthenticatedVentasIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/otp'
    | '/settings'
    | '/iniciar-sesion'
    | '/recuperar-cuenta'
    | '/registrar-negocio'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/dashboard'
    | '/client-portal/access'
    | '/'
    | '/link-iniciar-sesion/$token'
    | '/restablecer-contrasena/$token'
    | '/orden/historial'
    | '/settings/account'
    | '/settings/ai-assistant'
    | '/settings/categories'
    | '/settings/conversation-statuses'
    | '/settings/message-templates'
    | '/settings/quick-responses'
    | '/settings/roles'
    | '/settings/tags'
    | '/settings/units'
    | '/settings/whatsapp'
    | '/chats'
    | '/citas'
    | '/clientes'
    | '/empleados'
    | '/eventos'
    | '/orden'
    | '/paquetes'
    | '/productos'
    | '/servicios'
    | '/settings/'
    | '/tools'
    | '/ventas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/otp'
    | '/iniciar-sesion'
    | '/recuperar-cuenta'
    | '/registrar-negocio'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/dashboard'
    | '/client-portal/access'
    | '/'
    | '/link-iniciar-sesion/$token'
    | '/restablecer-contrasena/$token'
    | '/orden/historial'
    | '/settings/account'
    | '/settings/ai-assistant'
    | '/settings/categories'
    | '/settings/conversation-statuses'
    | '/settings/message-templates'
    | '/settings/quick-responses'
    | '/settings/roles'
    | '/settings/tags'
    | '/settings/units'
    | '/settings/whatsapp'
    | '/chats'
    | '/citas'
    | '/clientes'
    | '/empleados'
    | '/eventos'
    | '/orden'
    | '/paquetes'
    | '/productos'
    | '/servicios'
    | '/settings'
    | '/tools'
    | '/ventas'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/otp'
    | '/_authenticated/settings'
    | '/(auth)/iniciar-sesion'
    | '/(auth)/recuperar-cuenta'
    | '/(auth)/registrar-negocio'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/dashboard'
    | '/client-portal/access'
    | '/_authenticated/'
    | '/(auth)/link-iniciar-sesion/$token'
    | '/(auth)/restablecer-contrasena/$token'
    | '/_authenticated/orden/historial'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/ai-assistant'
    | '/_authenticated/settings/categories'
    | '/_authenticated/settings/conversation-statuses'
    | '/_authenticated/settings/message-templates'
    | '/_authenticated/settings/quick-responses'
    | '/_authenticated/settings/roles'
    | '/_authenticated/settings/tags'
    | '/_authenticated/settings/units'
    | '/_authenticated/settings/whatsapp'
    | '/_authenticated/chats/'
    | '/_authenticated/citas/'
    | '/_authenticated/clientes/'
    | '/_authenticated/empleados/'
    | '/_authenticated/eventos/'
    | '/_authenticated/orden/'
    | '/_authenticated/paquetes/'
    | '/_authenticated/productos/'
    | '/_authenticated/servicios/'
    | '/_authenticated/settings/'
    | '/_authenticated/tools/'
    | '/_authenticated/ventas/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authOtpRoute: typeof authOtpRoute
  authIniciarSesionLazyRoute: typeof authIniciarSesionLazyRoute
  authRecuperarCuentaLazyRoute: typeof authRecuperarCuentaLazyRoute
  authRegistrarNegocioLazyRoute: typeof authRegistrarNegocioLazyRoute
  authSignUpLazyRoute: typeof authSignUpLazyRoute
  errors401LazyRoute: typeof errors401LazyRoute
  errors403LazyRoute: typeof errors403LazyRoute
  errors404LazyRoute: typeof errors404LazyRoute
  errors500LazyRoute: typeof errors500LazyRoute
  errors503LazyRoute: typeof errors503LazyRoute
  ClientPortalAccessLazyRoute: typeof ClientPortalAccessLazyRoute
  authLinkIniciarSesionTokenRoute: typeof authLinkIniciarSesionTokenRoute
  authRestablecerContrasenaTokenRoute: typeof authRestablecerContrasenaTokenRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authOtpRoute: authOtpRoute,
  authIniciarSesionLazyRoute: authIniciarSesionLazyRoute,
  authRecuperarCuentaLazyRoute: authRecuperarCuentaLazyRoute,
  authRegistrarNegocioLazyRoute: authRegistrarNegocioLazyRoute,
  authSignUpLazyRoute: authSignUpLazyRoute,
  errors401LazyRoute: errors401LazyRoute,
  errors403LazyRoute: errors403LazyRoute,
  errors404LazyRoute: errors404LazyRoute,
  errors500LazyRoute: errors500LazyRoute,
  errors503LazyRoute: errors503LazyRoute,
  ClientPortalAccessLazyRoute: ClientPortalAccessLazyRoute,
  authLinkIniciarSesionTokenRoute: authLinkIniciarSesionTokenRoute,
  authRestablecerContrasenaTokenRoute: authRestablecerContrasenaTokenRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/(auth)/otp",
        "/(auth)/iniciar-sesion",
        "/(auth)/recuperar-cuenta",
        "/(auth)/registrar-negocio",
        "/(auth)/sign-up",
        "/(errors)/401",
        "/(errors)/403",
        "/(errors)/404",
        "/(errors)/500",
        "/(errors)/503",
        "/client-portal/access",
        "/(auth)/link-iniciar-sesion/$token",
        "/(auth)/restablecer-contrasena/$token"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated/route.tsx",
      "children": [
        "/_authenticated/settings",
        "/_authenticated/dashboard",
        "/_authenticated/",
        "/_authenticated/orden/historial",
        "/_authenticated/chats/",
        "/_authenticated/citas/",
        "/_authenticated/clientes/",
        "/_authenticated/empleados/",
        "/_authenticated/eventos/",
        "/_authenticated/orden/",
        "/_authenticated/paquetes/",
        "/_authenticated/productos/",
        "/_authenticated/servicios/",
        "/_authenticated/tools/",
        "/_authenticated/ventas/"
      ]
    },
    "/(auth)/otp": {
      "filePath": "(auth)/otp.tsx"
    },
    "/_authenticated/settings": {
      "filePath": "_authenticated/settings/route.lazy.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/settings/account",
        "/_authenticated/settings/ai-assistant",
        "/_authenticated/settings/categories",
        "/_authenticated/settings/conversation-statuses",
        "/_authenticated/settings/message-templates",
        "/_authenticated/settings/quick-responses",
        "/_authenticated/settings/roles",
        "/_authenticated/settings/tags",
        "/_authenticated/settings/units",
        "/_authenticated/settings/whatsapp",
        "/_authenticated/settings/"
      ]
    },
    "/(auth)/iniciar-sesion": {
      "filePath": "(auth)/iniciar-sesion.lazy.tsx"
    },
    "/(auth)/recuperar-cuenta": {
      "filePath": "(auth)/recuperar-cuenta.lazy.tsx"
    },
    "/(auth)/registrar-negocio": {
      "filePath": "(auth)/registrar-negocio.lazy.tsx"
    },
    "/(auth)/sign-up": {
      "filePath": "(auth)/sign-up.lazy.tsx"
    },
    "/(errors)/401": {
      "filePath": "(errors)/401.lazy.tsx"
    },
    "/(errors)/403": {
      "filePath": "(errors)/403.lazy.tsx"
    },
    "/(errors)/404": {
      "filePath": "(errors)/404.lazy.tsx"
    },
    "/(errors)/500": {
      "filePath": "(errors)/500.lazy.tsx"
    },
    "/(errors)/503": {
      "filePath": "(errors)/503.lazy.tsx"
    },
    "/_authenticated/dashboard": {
      "filePath": "_authenticated/dashboard.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/client-portal/access": {
      "filePath": "client-portal/access.lazy.tsx"
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.tsx",
      "parent": "/_authenticated"
    },
    "/(auth)/link-iniciar-sesion/$token": {
      "filePath": "(auth)/link-iniciar-sesion.$token.tsx"
    },
    "/(auth)/restablecer-contrasena/$token": {
      "filePath": "(auth)/restablecer-contrasena.$token.tsx"
    },
    "/_authenticated/orden/historial": {
      "filePath": "_authenticated/orden/historial.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/settings/account": {
      "filePath": "_authenticated/settings/account.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/ai-assistant": {
      "filePath": "_authenticated/settings/ai-assistant.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/categories": {
      "filePath": "_authenticated/settings/categories.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/conversation-statuses": {
      "filePath": "_authenticated/settings/conversation-statuses.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/message-templates": {
      "filePath": "_authenticated/settings/message-templates.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/quick-responses": {
      "filePath": "_authenticated/settings/quick-responses.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/roles": {
      "filePath": "_authenticated/settings/roles.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/tags": {
      "filePath": "_authenticated/settings/tags.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/units": {
      "filePath": "_authenticated/settings/units.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/whatsapp": {
      "filePath": "_authenticated/settings/whatsapp.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/chats/": {
      "filePath": "_authenticated/chats/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/citas/": {
      "filePath": "_authenticated/citas/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/clientes/": {
      "filePath": "_authenticated/clientes/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/empleados/": {
      "filePath": "_authenticated/empleados/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/eventos/": {
      "filePath": "_authenticated/eventos/index.lazy.ts",
      "parent": "/_authenticated"
    },
    "/_authenticated/orden/": {
      "filePath": "_authenticated/orden/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/paquetes/": {
      "filePath": "_authenticated/paquetes/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/productos/": {
      "filePath": "_authenticated/productos/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/servicios/": {
      "filePath": "_authenticated/servicios/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/settings/": {
      "filePath": "_authenticated/settings/index.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/tools/": {
      "filePath": "_authenticated/tools/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/ventas/": {
      "filePath": "_authenticated/ventas/index.lazy.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
