/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index'
import { Route as authOtpImport } from './routes/(auth)/otp'
import { Route as AuthenticatedChatsIndexImport } from './routes/_authenticated/chats/index'
import { Route as authRestablecerContrasenaTokenImport } from './routes/(auth)/restablecer-contrasena.$token'
import { Route as authLinkIniciarSesionTokenImport } from './routes/(auth)/link-iniciar-sesion.$token'

// Create Virtual Routes

const errors503LazyImport = createFileRoute('/(errors)/503')()
const errors500LazyImport = createFileRoute('/(errors)/500')()
const errors404LazyImport = createFileRoute('/(errors)/404')()
const errors403LazyImport = createFileRoute('/(errors)/403')()
const errors401LazyImport = createFileRoute('/(errors)/401')()
const authSignUpLazyImport = createFileRoute('/(auth)/sign-up')()
const authRecuperarCuentaLazyImport = createFileRoute(
  '/(auth)/recuperar-cuenta',
)()
const authIniciarSesionLazyImport = createFileRoute('/(auth)/iniciar-sesion')()
const AuthenticatedSettingsRouteLazyImport = createFileRoute(
  '/_authenticated/settings',
)()
const AuthenticatedSettingsIndexLazyImport = createFileRoute(
  '/_authenticated/settings/',
)()
const AuthenticatedServiciosIndexLazyImport = createFileRoute(
  '/_authenticated/servicios/',
)()
const AuthenticatedEventosIndexLazyImport = createFileRoute(
  '/_authenticated/eventos/',
)()
const AuthenticatedEmpleadosIndexLazyImport = createFileRoute(
  '/_authenticated/empleados/',
)()
const AuthenticatedClientesIndexLazyImport = createFileRoute(
  '/_authenticated/clientes/',
)()
const AuthenticatedCitasIndexLazyImport = createFileRoute(
  '/_authenticated/citas/',
)()
const AuthenticatedSettingsWhatsappLazyImport = createFileRoute(
  '/_authenticated/settings/whatsapp',
)()
const AuthenticatedSettingsNotificationsLazyImport = createFileRoute(
  '/_authenticated/settings/notifications',
)()
const AuthenticatedSettingsDisplayLazyImport = createFileRoute(
  '/_authenticated/settings/display',
)()
const AuthenticatedSettingsAccountLazyImport = createFileRoute(
  '/_authenticated/settings/account',
)()

// Create/Update Routes

const AuthenticatedRouteRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const errors503LazyRoute = errors503LazyImport
  .update({
    id: '/(errors)/503',
    path: '/503',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/503.lazy').then((d) => d.Route))

const errors500LazyRoute = errors500LazyImport
  .update({
    id: '/(errors)/500',
    path: '/500',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/500.lazy').then((d) => d.Route))

const errors404LazyRoute = errors404LazyImport
  .update({
    id: '/(errors)/404',
    path: '/404',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/404.lazy').then((d) => d.Route))

const errors403LazyRoute = errors403LazyImport
  .update({
    id: '/(errors)/403',
    path: '/403',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/403.lazy').then((d) => d.Route))

const errors401LazyRoute = errors401LazyImport
  .update({
    id: '/(errors)/401',
    path: '/401',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/401.lazy').then((d) => d.Route))

const authSignUpLazyRoute = authSignUpLazyImport
  .update({
    id: '/(auth)/sign-up',
    path: '/sign-up',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(auth)/sign-up.lazy').then((d) => d.Route))

const authRecuperarCuentaLazyRoute = authRecuperarCuentaLazyImport
  .update({
    id: '/(auth)/recuperar-cuenta',
    path: '/recuperar-cuenta',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() =>
    import('./routes/(auth)/recuperar-cuenta.lazy').then((d) => d.Route),
  )

const authIniciarSesionLazyRoute = authIniciarSesionLazyImport
  .update({
    id: '/(auth)/iniciar-sesion',
    path: '/iniciar-sesion',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() =>
    import('./routes/(auth)/iniciar-sesion.lazy').then((d) => d.Route),
  )

const AuthenticatedSettingsRouteLazyRoute =
  AuthenticatedSettingsRouteLazyImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/route.lazy').then((d) => d.Route),
  )

const authOtpRoute = authOtpImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedSettingsIndexLazyRoute =
  AuthenticatedSettingsIndexLazyImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/index.lazy').then((d) => d.Route),
  )

const AuthenticatedServiciosIndexLazyRoute =
  AuthenticatedServiciosIndexLazyImport.update({
    id: '/servicios/',
    path: '/servicios/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/servicios/index.lazy').then((d) => d.Route),
  )

const AuthenticatedEventosIndexLazyRoute =
  AuthenticatedEventosIndexLazyImport.update({
    id: '/eventos/',
    path: '/eventos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/eventos/index.lazy').then((d) => d.Route),
  )

const AuthenticatedEmpleadosIndexLazyRoute =
  AuthenticatedEmpleadosIndexLazyImport.update({
    id: '/empleados/',
    path: '/empleados/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/empleados/index.lazy').then((d) => d.Route),
  )

const AuthenticatedClientesIndexLazyRoute =
  AuthenticatedClientesIndexLazyImport.update({
    id: '/clientes/',
    path: '/clientes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/clientes/index.lazy').then((d) => d.Route),
  )

const AuthenticatedCitasIndexLazyRoute =
  AuthenticatedCitasIndexLazyImport.update({
    id: '/citas/',
    path: '/citas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/citas/index.lazy').then((d) => d.Route),
  )

const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedSettingsWhatsappLazyRoute =
  AuthenticatedSettingsWhatsappLazyImport.update({
    id: '/whatsapp',
    path: '/whatsapp',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/whatsapp.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedSettingsNotificationsLazyRoute =
  AuthenticatedSettingsNotificationsLazyImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/notifications.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedSettingsDisplayLazyRoute =
  AuthenticatedSettingsDisplayLazyImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/display.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedSettingsAccountLazyRoute =
  AuthenticatedSettingsAccountLazyImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/account.lazy').then(
      (d) => d.Route,
    ),
  )

const authRestablecerContrasenaTokenRoute =
  authRestablecerContrasenaTokenImport.update({
    id: '/(auth)/restablecer-contrasena/$token',
    path: '/restablecer-contrasena/$token',
    getParentRoute: () => rootRoute,
  } as any)

const authLinkIniciarSesionTokenRoute = authLinkIniciarSesionTokenImport.update(
  {
    id: '/(auth)/link-iniciar-sesion/$token',
    path: '/link-iniciar-sesion/$token',
    getParentRoute: () => rootRoute,
  } as any,
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/(auth)/iniciar-sesion': {
      id: '/(auth)/iniciar-sesion'
      path: '/iniciar-sesion'
      fullPath: '/iniciar-sesion'
      preLoaderRoute: typeof authIniciarSesionLazyImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/recuperar-cuenta': {
      id: '/(auth)/recuperar-cuenta'
      path: '/recuperar-cuenta'
      fullPath: '/recuperar-cuenta'
      preLoaderRoute: typeof authRecuperarCuentaLazyImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpLazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503LazyImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/(auth)/link-iniciar-sesion/$token': {
      id: '/(auth)/link-iniciar-sesion/$token'
      path: '/link-iniciar-sesion/$token'
      fullPath: '/link-iniciar-sesion/$token'
      preLoaderRoute: typeof authLinkIniciarSesionTokenImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/restablecer-contrasena/$token': {
      id: '/(auth)/restablecer-contrasena/$token'
      path: '/restablecer-contrasena/$token'
      fullPath: '/restablecer-contrasena/$token'
      preLoaderRoute: typeof authRestablecerContrasenaTokenImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountLazyImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayLazyImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsLazyImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/settings/whatsapp': {
      id: '/_authenticated/settings/whatsapp'
      path: '/whatsapp'
      fullPath: '/settings/whatsapp'
      preLoaderRoute: typeof AuthenticatedSettingsWhatsappLazyImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/citas/': {
      id: '/_authenticated/citas/'
      path: '/citas'
      fullPath: '/citas'
      preLoaderRoute: typeof AuthenticatedCitasIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/clientes/': {
      id: '/_authenticated/clientes/'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/empleados/': {
      id: '/_authenticated/empleados/'
      path: '/empleados'
      fullPath: '/empleados'
      preLoaderRoute: typeof AuthenticatedEmpleadosIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/eventos/': {
      id: '/_authenticated/eventos/'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof AuthenticatedEventosIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/servicios/': {
      id: '/_authenticated/servicios/'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof AuthenticatedServiciosIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexLazyImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedSettingsRouteLazyRouteChildren {
  AuthenticatedSettingsAccountLazyRoute: typeof AuthenticatedSettingsAccountLazyRoute
  AuthenticatedSettingsDisplayLazyRoute: typeof AuthenticatedSettingsDisplayLazyRoute
  AuthenticatedSettingsNotificationsLazyRoute: typeof AuthenticatedSettingsNotificationsLazyRoute
  AuthenticatedSettingsWhatsappLazyRoute: typeof AuthenticatedSettingsWhatsappLazyRoute
  AuthenticatedSettingsIndexLazyRoute: typeof AuthenticatedSettingsIndexLazyRoute
}

const AuthenticatedSettingsRouteLazyRouteChildren: AuthenticatedSettingsRouteLazyRouteChildren =
  {
    AuthenticatedSettingsAccountLazyRoute:
      AuthenticatedSettingsAccountLazyRoute,
    AuthenticatedSettingsDisplayLazyRoute:
      AuthenticatedSettingsDisplayLazyRoute,
    AuthenticatedSettingsNotificationsLazyRoute:
      AuthenticatedSettingsNotificationsLazyRoute,
    AuthenticatedSettingsWhatsappLazyRoute:
      AuthenticatedSettingsWhatsappLazyRoute,
    AuthenticatedSettingsIndexLazyRoute: AuthenticatedSettingsIndexLazyRoute,
  }

const AuthenticatedSettingsRouteLazyRouteWithChildren =
  AuthenticatedSettingsRouteLazyRoute._addFileChildren(
    AuthenticatedSettingsRouteLazyRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteLazyRoute: typeof AuthenticatedSettingsRouteLazyRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedCitasIndexLazyRoute: typeof AuthenticatedCitasIndexLazyRoute
  AuthenticatedClientesIndexLazyRoute: typeof AuthenticatedClientesIndexLazyRoute
  AuthenticatedEmpleadosIndexLazyRoute: typeof AuthenticatedEmpleadosIndexLazyRoute
  AuthenticatedEventosIndexLazyRoute: typeof AuthenticatedEventosIndexLazyRoute
  AuthenticatedServiciosIndexLazyRoute: typeof AuthenticatedServiciosIndexLazyRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteLazyRoute:
    AuthenticatedSettingsRouteLazyRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedCitasIndexLazyRoute: AuthenticatedCitasIndexLazyRoute,
  AuthenticatedClientesIndexLazyRoute: AuthenticatedClientesIndexLazyRoute,
  AuthenticatedEmpleadosIndexLazyRoute: AuthenticatedEmpleadosIndexLazyRoute,
  AuthenticatedEventosIndexLazyRoute: AuthenticatedEventosIndexLazyRoute,
  AuthenticatedServiciosIndexLazyRoute: AuthenticatedServiciosIndexLazyRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedRouteRouteWithChildren
  '/otp': typeof authOtpRoute
  '/settings': typeof AuthenticatedSettingsRouteLazyRouteWithChildren
  '/iniciar-sesion': typeof authIniciarSesionLazyRoute
  '/recuperar-cuenta': typeof authRecuperarCuentaLazyRoute
  '/sign-up': typeof authSignUpLazyRoute
  '/401': typeof errors401LazyRoute
  '/403': typeof errors403LazyRoute
  '/404': typeof errors404LazyRoute
  '/500': typeof errors500LazyRoute
  '/503': typeof errors503LazyRoute
  '/': typeof AuthenticatedIndexRoute
  '/link-iniciar-sesion/$token': typeof authLinkIniciarSesionTokenRoute
  '/restablecer-contrasena/$token': typeof authRestablecerContrasenaTokenRoute
  '/settings/account': typeof AuthenticatedSettingsAccountLazyRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayLazyRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsLazyRoute
  '/settings/whatsapp': typeof AuthenticatedSettingsWhatsappLazyRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/citas': typeof AuthenticatedCitasIndexLazyRoute
  '/clientes': typeof AuthenticatedClientesIndexLazyRoute
  '/empleados': typeof AuthenticatedEmpleadosIndexLazyRoute
  '/eventos': typeof AuthenticatedEventosIndexLazyRoute
  '/servicios': typeof AuthenticatedServiciosIndexLazyRoute
  '/settings/': typeof AuthenticatedSettingsIndexLazyRoute
}

export interface FileRoutesByTo {
  '/otp': typeof authOtpRoute
  '/iniciar-sesion': typeof authIniciarSesionLazyRoute
  '/recuperar-cuenta': typeof authRecuperarCuentaLazyRoute
  '/sign-up': typeof authSignUpLazyRoute
  '/401': typeof errors401LazyRoute
  '/403': typeof errors403LazyRoute
  '/404': typeof errors404LazyRoute
  '/500': typeof errors500LazyRoute
  '/503': typeof errors503LazyRoute
  '/': typeof AuthenticatedIndexRoute
  '/link-iniciar-sesion/$token': typeof authLinkIniciarSesionTokenRoute
  '/restablecer-contrasena/$token': typeof authRestablecerContrasenaTokenRoute
  '/settings/account': typeof AuthenticatedSettingsAccountLazyRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayLazyRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsLazyRoute
  '/settings/whatsapp': typeof AuthenticatedSettingsWhatsappLazyRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/citas': typeof AuthenticatedCitasIndexLazyRoute
  '/clientes': typeof AuthenticatedClientesIndexLazyRoute
  '/empleados': typeof AuthenticatedEmpleadosIndexLazyRoute
  '/eventos': typeof AuthenticatedEventosIndexLazyRoute
  '/servicios': typeof AuthenticatedServiciosIndexLazyRoute
  '/settings': typeof AuthenticatedSettingsIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/otp': typeof authOtpRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteLazyRouteWithChildren
  '/(auth)/iniciar-sesion': typeof authIniciarSesionLazyRoute
  '/(auth)/recuperar-cuenta': typeof authRecuperarCuentaLazyRoute
  '/(auth)/sign-up': typeof authSignUpLazyRoute
  '/(errors)/401': typeof errors401LazyRoute
  '/(errors)/403': typeof errors403LazyRoute
  '/(errors)/404': typeof errors404LazyRoute
  '/(errors)/500': typeof errors500LazyRoute
  '/(errors)/503': typeof errors503LazyRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/(auth)/link-iniciar-sesion/$token': typeof authLinkIniciarSesionTokenRoute
  '/(auth)/restablecer-contrasena/$token': typeof authRestablecerContrasenaTokenRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountLazyRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayLazyRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsLazyRoute
  '/_authenticated/settings/whatsapp': typeof AuthenticatedSettingsWhatsappLazyRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/citas/': typeof AuthenticatedCitasIndexLazyRoute
  '/_authenticated/clientes/': typeof AuthenticatedClientesIndexLazyRoute
  '/_authenticated/empleados/': typeof AuthenticatedEmpleadosIndexLazyRoute
  '/_authenticated/eventos/': typeof AuthenticatedEventosIndexLazyRoute
  '/_authenticated/servicios/': typeof AuthenticatedServiciosIndexLazyRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/otp'
    | '/settings'
    | '/iniciar-sesion'
    | '/recuperar-cuenta'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/link-iniciar-sesion/$token'
    | '/restablecer-contrasena/$token'
    | '/settings/account'
    | '/settings/display'
    | '/settings/notifications'
    | '/settings/whatsapp'
    | '/chats'
    | '/citas'
    | '/clientes'
    | '/empleados'
    | '/eventos'
    | '/servicios'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/otp'
    | '/iniciar-sesion'
    | '/recuperar-cuenta'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/link-iniciar-sesion/$token'
    | '/restablecer-contrasena/$token'
    | '/settings/account'
    | '/settings/display'
    | '/settings/notifications'
    | '/settings/whatsapp'
    | '/chats'
    | '/citas'
    | '/clientes'
    | '/empleados'
    | '/eventos'
    | '/servicios'
    | '/settings'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/otp'
    | '/_authenticated/settings'
    | '/(auth)/iniciar-sesion'
    | '/(auth)/recuperar-cuenta'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/(auth)/link-iniciar-sesion/$token'
    | '/(auth)/restablecer-contrasena/$token'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/settings/whatsapp'
    | '/_authenticated/chats/'
    | '/_authenticated/citas/'
    | '/_authenticated/clientes/'
    | '/_authenticated/empleados/'
    | '/_authenticated/eventos/'
    | '/_authenticated/servicios/'
    | '/_authenticated/settings/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authOtpRoute: typeof authOtpRoute
  authIniciarSesionLazyRoute: typeof authIniciarSesionLazyRoute
  authRecuperarCuentaLazyRoute: typeof authRecuperarCuentaLazyRoute
  authSignUpLazyRoute: typeof authSignUpLazyRoute
  errors401LazyRoute: typeof errors401LazyRoute
  errors403LazyRoute: typeof errors403LazyRoute
  errors404LazyRoute: typeof errors404LazyRoute
  errors500LazyRoute: typeof errors500LazyRoute
  errors503LazyRoute: typeof errors503LazyRoute
  authLinkIniciarSesionTokenRoute: typeof authLinkIniciarSesionTokenRoute
  authRestablecerContrasenaTokenRoute: typeof authRestablecerContrasenaTokenRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authOtpRoute: authOtpRoute,
  authIniciarSesionLazyRoute: authIniciarSesionLazyRoute,
  authRecuperarCuentaLazyRoute: authRecuperarCuentaLazyRoute,
  authSignUpLazyRoute: authSignUpLazyRoute,
  errors401LazyRoute: errors401LazyRoute,
  errors403LazyRoute: errors403LazyRoute,
  errors404LazyRoute: errors404LazyRoute,
  errors500LazyRoute: errors500LazyRoute,
  errors503LazyRoute: errors503LazyRoute,
  authLinkIniciarSesionTokenRoute: authLinkIniciarSesionTokenRoute,
  authRestablecerContrasenaTokenRoute: authRestablecerContrasenaTokenRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/(auth)/otp",
        "/(auth)/iniciar-sesion",
        "/(auth)/recuperar-cuenta",
        "/(auth)/sign-up",
        "/(errors)/401",
        "/(errors)/403",
        "/(errors)/404",
        "/(errors)/500",
        "/(errors)/503",
        "/(auth)/link-iniciar-sesion/$token",
        "/(auth)/restablecer-contrasena/$token"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated/route.tsx",
      "children": [
        "/_authenticated/settings",
        "/_authenticated/",
        "/_authenticated/chats/",
        "/_authenticated/citas/",
        "/_authenticated/clientes/",
        "/_authenticated/empleados/",
        "/_authenticated/eventos/",
        "/_authenticated/servicios/"
      ]
    },
    "/(auth)/otp": {
      "filePath": "(auth)/otp.tsx"
    },
    "/_authenticated/settings": {
      "filePath": "_authenticated/settings/route.lazy.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/settings/account",
        "/_authenticated/settings/display",
        "/_authenticated/settings/notifications",
        "/_authenticated/settings/whatsapp",
        "/_authenticated/settings/"
      ]
    },
    "/(auth)/iniciar-sesion": {
      "filePath": "(auth)/iniciar-sesion.lazy.tsx"
    },
    "/(auth)/recuperar-cuenta": {
      "filePath": "(auth)/recuperar-cuenta.lazy.tsx"
    },
    "/(auth)/sign-up": {
      "filePath": "(auth)/sign-up.lazy.tsx"
    },
    "/(errors)/401": {
      "filePath": "(errors)/401.lazy.tsx"
    },
    "/(errors)/403": {
      "filePath": "(errors)/403.lazy.tsx"
    },
    "/(errors)/404": {
      "filePath": "(errors)/404.lazy.tsx"
    },
    "/(errors)/500": {
      "filePath": "(errors)/500.lazy.tsx"
    },
    "/(errors)/503": {
      "filePath": "(errors)/503.lazy.tsx"
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.tsx",
      "parent": "/_authenticated"
    },
    "/(auth)/link-iniciar-sesion/$token": {
      "filePath": "(auth)/link-iniciar-sesion.$token.tsx"
    },
    "/(auth)/restablecer-contrasena/$token": {
      "filePath": "(auth)/restablecer-contrasena.$token.tsx"
    },
    "/_authenticated/settings/account": {
      "filePath": "_authenticated/settings/account.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/display": {
      "filePath": "_authenticated/settings/display.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/notifications": {
      "filePath": "_authenticated/settings/notifications.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/whatsapp": {
      "filePath": "_authenticated/settings/whatsapp.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/chats/": {
      "filePath": "_authenticated/chats/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/citas/": {
      "filePath": "_authenticated/citas/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/clientes/": {
      "filePath": "_authenticated/clientes/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/empleados/": {
      "filePath": "_authenticated/empleados/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/eventos/": {
      "filePath": "_authenticated/eventos/index.lazy.ts",
      "parent": "/_authenticated"
    },
    "/_authenticated/servicios/": {
      "filePath": "_authenticated/servicios/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/settings/": {
      "filePath": "_authenticated/settings/index.lazy.tsx",
      "parent": "/_authenticated/settings"
    }
  }
}
ROUTE_MANIFEST_END */
