name: Deploy to Vercel QA

on:
  push:
    branches:
      - qa

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel (QA)
        run: |
          export VERCEL_PROJECT_ID=${{ secrets.VERCEL_QA_PROJECT_ID }}
          export VERCEL_ORG_ID=${{ secrets.VERCEL_QA_ORG_ID }}
          export VERCEL_TOKEN=${{ secrets.VERCEL_TOKEN }}

          vercel --confirm --prod --token $VERCEL_TOKEN